config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root home route
  root :to => 'pages#index'
  #get '/about' => 'pages#terms' disable this function for temporary
  get '/terms_privacy' => 'pages#terms_privacy'

  #admin user login route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #user registrations route - devise gem
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'}
              #controllers: {registrations: 'registrations'}

  # get 'tasks/show'
  get 'project/index'

  #get myproject/list
  get '/myprojects' => 'project#list'

  #subscriptions route
  post '/free' => 'charge#free'
  #subscription with stripe route
  post '/pay' => 'charge#pay'
  # get 'projects/show'
  resources :project do
    resources :task, only: [:show]
  end

  #get reviews to project
  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    #Add friendly_id 
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]
    #tasks association
    has_many :tasks
    #subscriptions association
    has_many :subscriptions
    has_many :users, through: :subscriptions
    
    #review project
    has_many :reviews
    #add image to project
    #has_one_attached :image # disable im,age upload temporary

    #validate project
    validates :name, presence: true, length: { maximum: 100 }
    validates :content, presence: true, length: { maximum: 1000 }
    validates :price, presence: true, numericality: { only_integer: true }

    #Implemnted legth text 
    def shortname
        name.length > 80? name[0..80] + "..." : name
    end

    #implemntas project stars
    def average_rating
        reviews.blank? ? 0 : reviews.average(:star).round(2)
    end

    #Convert price to cents
    def price_in_cents
        price*100
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  #Add friendly_id 
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :project

  validates :title, presence: true, length: { maximum: 200 }
  #validates :video, presence: true
  #validates :tag, presence: true
  validates :project, presence: true

  #Implemnted next button
  def next
    project.tasks.where("tag > ? AND header = ?", tag, false).order(:tag).first
  end

  #Implemnted preview button
  def prev
    project.tasks.where("tag < ? AND header = ?", tag, false).order(:tag).last
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:lockable, :timeoutable, :trackable and :omniauthable

  #Declave Avatar image
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  #Declarated Fullname register with devise
  validates :fullname, presence: true, length: {maximum: 25}
  #subscriptions association
  has_many :subscriptions
  has_many :projects, through: :subscriptions

  #review project
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #config devise with fullname register
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
    end
    #end config
end

app/controllers/charge_controller.rb
class ChargeController < ApplicationController
    before_action :authenticate_user!
    #free subscription
    def free
        project = Project.find(params[:project_id])
        current_user.subscriptions.create(project: project)

        redirect_to project
    end

    #Subscription with Stripe
    def pay
        #Select the project id
        project = Project.find(params[:project_id])
        #stripe custom
        customer = Stripe::Customer.create({
            email: params[:stripeEmail],
            source: params[:stripeToken],
        })

        charge = Stripe::Charge.create({
            customer: customer.id,
            amount: project.price_in_cents,
            description: project.name,
            currency: 'usd',
        })

        if charge
            current_user.subscriptions.create(project: project)
            redirect_to project, notice: "Thank you for your purchase. Check your email to see your receipt." 
        end

    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to project
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  # def about disable this function for temporary
  # end

  def terms_privacy
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, only: [:list]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(:tag)

    #validate access to project with subscription
    @joined = false

    if !current_user.nil? && !current_user.projects.nil?
      @joined = current_user.projects.include?(@project)
    end

    #Review validates
    @review = Review.new
    @reviews = @project.reviews
    #check if has review
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  #myproject list
  def list
    if !current_user.nil?
      @projects = current_user.projects
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    def create
        @review = Review.create(review_params)
        project = @review.project

        redirect_to project
    end

    def destroy
        @review = Review.find(params[:id])
        project = @review.project
        @review.destroy

        redirect_to project
    end

    private

    def review_params
        params.require(:review).permit(:star, :comment, :project_id, :user_id)
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!

  def show
    project = Project.find(params[:project_id])
    @tasks = project.tasks.order(:tag)
    @task = @tasks.find(params[:id])

    #validate access to project with subscription
    joined = false

    if !current_user.nil? && !current_user.projects.nil?
      joined = current_user.projects.include?(project)
    end

    #next and prev buttons  before buy the project
    if joined
      @task = @tasks.find(params[:id])
      @next_task = @task.next
      @prev_task = @task.prev
    else
      flash[:alert] = "You don't have permission for this project!"
      redirect_to project
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        if user.avatar.attached?
            url_for(user.avatar)
        # elsif user.image?
        #     user.image
        else
            ActionController::Base.helpers.asset_path('avatar_default.svg')
        end
    end

    # IMPLENTED CODERAY
    class CodeRayifty < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language).div(:line_numbers => :table)
        end
    end

    # IMPLENTED MARKDOWN
    def markdown(text)
        coderayified = CodeRayifty.new(:filter_html => true, :hard_wrap => true)
        options = {
            :fenced_code_blocks  => true,
            :no_intra_emphasis  => true,
            :autolink  => true,
            :strikethrough  => true,
            :lax_spacing  => true,
            :superscript  => true
        }
        
        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>HiGoLearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow"/>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'src/application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add Google Font  -->
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.14.0/css/all.css">
    <!-- Global Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177081278-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-177081278-1');
    </script>
    <meta property="og:image" content="https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500">
    <!-- End Google Tag Manager -->
    <!--Social media column-->
    <%= yield :head %>
    <!--Social media column end/-->
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12 pt-3 pb-3 mb4">
          <!--navbar-->
          <%= render 'shared/navbar' %>
          <!--notification-->
          <%= render 'shared/message' %>

          <%= yield %>

        </div>
      </div>
    </div>
    <!-- End of Chaport Live Chat code -->
  </body>
</html>  

app/views/pages/home.html.erb
<!-- Jumbotron Header -->
<header class="jumbotron my-4 text-center">
    <h2 class="jumbotron-title">Bienvenido a <strong>HiGoLearn</strong></h2>
    <p>
        Aprende a crear Paginas Web, Aplicaciones y Video Juegos desde lo básico hasta crear <strong>Startups</strong><br>
        de la vida real. Con <strong>Python</strong>, <strong>Django</strong>, <strong>Ruby</strong>, <strong>Rails</strong>, <strong>JavaScript</strong> y mucho más.
    </p>
    <%= image_tag 'monitor.svg', class: "img-responsive", alt: "Jumbotron Image" %> <br>
    <%= link_to 'Iniciar Aprender', project_index_path, class: "btn btn-form" %>
</header>

<div class="row mt-4">
    <div class="col text-center">
        <h2 class="text-tile">Características Asombrosas</h2>
    </div>
</div>
<br/>

<div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-4">
        <div class="card text-center">
            <%= image_tag 'question.svg', class: "img-circle feature-img-responsive mt-2", alt: "Feature Image 1" %>
            <div class="card-body">
                <h4 class="card-title feature-card-title">Newbie Level</h4>
                <p class="card-text">Usted aprendera los conceptos esenciales para dominar el arte de la programación.</p>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card text-center">
            <%= image_tag 'user-interface.svg', class: "img-circle feature-img-responsive mt-2", alt: "Feature Image 2" %>
            <div class="card-body">
                <h4 class="card-title feature-card-title">Expert Level</h4>
                <p class="card-text">Aprenderas programación orientada a objetos y metodología de diseño de Software con proyectos reales. </p>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card text-center">
            <%= image_tag 'mission.svg', class: "img-circle feature-img-responsive mt-2", alt: "Feature Image 3" %>
            <div class="card-body">
                <h4 class="card-title feature-card-title">Hero Level</h4>
                <p class="card-text">En este proyecto, los guiaré paso a paso para desarrollar aplicaciones reales como <Strong>UberEats</Strong> y <strong>Fiverr</strong> desde cero.</p>
            </div>
        </div>
    </div>
</div>
<br>

<div class="row justify-content-center mt-4">
    <div class="col-md-6 text-center">
        <h2 class="text-title">Próximamente - <strong>Newbie Level</strong></h2>
        <div class="card-body-lunch text-center" id="timer">
            <div class="time-card">
                <span class="time-count" id="days"></span>
                <span class="time-label">Days</span>
            </div>
            <div class="time-card">
                <span class="time-count" id="hours"></span>
                <span class="time-label">Hours</span>
            </div>
            <div class="time-card">
                <span class="time-count" id="minutes"></span>
                <span class="time-label">Minutes</span>
            </div>
            <div class="time-card">
                <span class="time-count" id="seconds"></span>
                <span class="time-label">Seconds</span>
            </div>
        </div>
    </div>
</div>
<br>
<hr/>
<br>
<%= render 'shared/footer' %>


<script>

    var endDate = new Date().getTime() + 2592000000;

    var x = setInterval(function() {

        var now =  new Date().getTime();

        var timeRemaining = endDate - now;

        var daysRemaining = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));
        var hoursRemaining = Math.floor((timeRemaining % (1000 * 60 * 60 * 24))/(1000 * 60 * 60));
        var minutesRemaining = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));
        var secondsRemaining = Math.floor((timeRemaining % (1000 * 60)) / (1000));

        document.getElementById("days").innerHTML = daysRemaining;
        document.getElementById("hours").innerHTML = hoursRemaining;
        document.getElementById("minutes").innerHTML = minutesRemaining;
        document.getElementById("seconds").innerHTML = secondsRemaining; 

        if (timeRemaining < 0) { 
            clearInterval(x);
            document.getElementById("days").innerHTML ='0'; 
            document.getElementById("hours").innerHTML ='0'; 
            document.getElementById("minutes").innerHTML ='0' ; 
            document.getElementById("seconds").innerHTML = '0';
            alert("Thank you for your patience");
        }

    },1000);
	
</script>

app/views/project/_payment.html.erb
<!--Stripe checkout pay old-->
<%= form_tag pay_path, id: 'chargeForm' do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= hidden_field_tag 'stripeToken' %>
    <%= hidden_field_tag 'stripeEmail' %>
    <%= hidden_field_tag 'project_id', @project.id %>
    <button id="customButton" id="customButton" class="btn btn-form">Start Project</button> <br/>
    
    <script>
        var handler = StripeCheckout.configure ({
            key:'<%= Rails.configuration.stripe[:publishable_key] %>',

            token: function(token, arg){
                $('#stripeToken').val(token.id);
                $('#stripeEmail').val(token.email);
                $('#chargeForm').submit();
            }
        });
        $('#customButton').on('click', function(e){
            handler.open({
                name: 'HiGoLearn',
                description: '<%= @project.name %>',
                amount: '<%= @project.price_in_cents %>',
                email: '<%= current_user.email %>',
            });
            e.preventDefault();
        });
        // $(window).on('popstate', function(){
        //     handler.close();
        // });
    </script>
<% end %>

app/views/project/index.html.erb
<div class="row mt-5">
    <div class="col text-center">
        <h2 class="text-tile">Proyectos</h2>
    </div>
</div>
<br>

<div class="row row-cols-1 row-cols-md-3" data-turbolinks="false">
    <% @projects.each do |project| %>
        <div class="col mb-4">
            <%= link_to project do %>
                <div class="card" style="height: 8em">
                    <%# if project.image.present? %>
                        <%#= image_tag project.image, class: "card-img-top" %> <!--, wheith: "100", height: "200"-->
                    <%# end %>
                    <div class="card-body">
                        <%= content_tag :h5, project.shortname, class: "card-title", style: "color: #00A699 !important;" %>
                        <h6 class="card-text"><small class="text-muted">Published <%= time_ago_in_words(project.created_at) %> ago. </small></h6> <br/>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

<hr/>
<div data-turbolinks="false">
    <%= render 'shared/footer' %>
</div>

app/views/project/list.html.erb
<div class="row mt-5">
    <div class="col text-center">
        <h2 class="text-tile">Mi Proyecto</h2>
    </div>
</div>
<br>




<% if  @projects.count > 0 %>
    <div class="row row-cols-1 row-cols-md-3" data-turbolinks="false">
        <% @projects.each do |project| %>
            <div class="col mb-4">
                <%= link_to project do %>
                    <div class="card">
                        <%# if project.image.present? %>
                            <%#= image_tag project.image, class: "card-img-top" %> <!--, wheith: "100", height: "200"-->
                        <%# end %>
                        <div class="card-body" style="height: 8em">
                            <%= content_tag :h5, project.shortname, class: "card-title", style: "color: #00A699 !important;" %> 
                            <h6 class="card-text"><small class="text-muted">Published <%= time_ago_in_words(project.created_at) %> ago. </small></h6><br/>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
<% else %>
        <div class="col text-center">
            <h2 class="text-tile">Actualmente no estás en ningún proyecto! <i class="far fa-frown"></i></h2>
            <%= link_to 'Seleccionar un Proyecto', project_index_path, class: "btn btn-normal btn-block" %><i class="fas fa-rocket"></i>
        </div>
<% end %>

app/views/project/show.html.erb
<% content_for :head  do %>
    <title><%= @project.name %> | HiGoLearn</title>
    <meta name="author" content="Jesus Almirco">
    <!--Twitter Card Data-->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@HiGoLearn">
    <meta name="twitter:creator" content="@HiGoLearn">
    <meta name="twitter:title" content="<%= @project.name %>">
    <meta name="twitter:description" content="<%= @project.content %>">
    <meta name="twitter:image:src" content="https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500">
    <!--Open Graph Data-->
    <meta property="og:site_name" content="HiGoLearn">
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%= @project.name %>">
    <meta property="og:description" content="<%= @project.content %>">
    <meta property="og:image" content="https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500">
<% end %>
<div class="row mt-5">
    <div class="col-lg-12 text-center">
        <%= content_tag :h3, @project.name, class: "text-title" %>
        <p>By - <strong>Jesus Almirco</strong></p>
    </div>
</div>
<br>

<!-- PROJECT DETAIL -->
<div class="row">
    <!-- LEFT CARD -->
    <div class="col-md-3" data-turbolinks="false">
        
        <div class="card mb-4 shadow-sm">
            <% if !@joined %>
                <div class="card-header text-center">
                    <%= content_tag :h1, @project.price == 0? "Free" : "$ #{@project.price}", class: "my-0 font-weight-normal" %>
                </div>
                <div class="card-body text-center">
                    
                    <h6 class="card-text"><i class="far fa-file-code"></i> Código Fuente</h6>
                    <h6 class="card-text"><i class="far fa-comments"></i> Discusión</h6>
                    <h6 class="card-text"><i class="far fa-hourglass"></i> Acceso de por Vida</h6>
                    <br>
                    <!--subscription form-->
                    <% if user_signed_in? %>
                        <% if @project.price == 0 %>
                            <%= form_tag free_path do %>
                                <%= hidden_field_tag 'project_id', @project.id %>
                                <button type="submit" class="btn btn-form">Iniciar Proyecto</button>
                            <% end %>
                        <% else %>
                            
                            <%= form_tag pay_path do %>
                                <article>
                                    <% if flash[:error].present? %>
                                        <div id="error_explanation">
                                            <p><%= flash[:error] %></p>
                                        </div>
                                    <% end %>
                                </article>
                                <%= hidden_field_tag 'project_id', @project.id %>

                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="<%= Rails.application.credentials.dig(Rails.env.to_sym, :stripe, :STRIPE_PUBLIC_KEY) %>"
                                    data-name="HiGoLearn"
                                    data-description="<%= @project.name %>"
                                    data-email="<%= current_user.email %>"
                                    data-amount="<%= @project.price_in_cents %>"
                                    data-locale="auto">
                                </script>
                            <% end %>
                        <% end %>
                    <% else %>
                        <%= link_to new_user_session_path do  %>
                            <button type="submit" class="btn btn-form">Iniciar Proyecto</button>
                        <% end %>
                    <% end %>

                </div>
            <% else %>
                <div class="card-body text-center">
                    <%= image_tag avatar_url(current_user), class: "img-circle avatar-medium" %><hr>
                    <span>
                        Welcome to this Project 
                    </span>
                    <%= content_tag :h5, truncate(current_user.fullname, :length => 17, :separator => ' ') %> <br>
                    <%= image_tag "party.svg", class: "img-circle avatar-medium" %> <br> <br>
                    <div id="average_rating"></div> 
                    <span> ( <%= @reviews.count %> <%= @reviews.count > 1? "Reviews" : "Review" %> )</span> <br><br>
                    <!--Review Modal-->
                    <%= render 'reviews/index' %>

                </div>
            <% end %>
        </div>
    </div>
    <!-- /LEFT CARD -->

    <!-- RIGHT CARD -->
    
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <ul class="nav nav-tabs justify-content-center" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active h-5" data-toggle="tab" href="#about" role="tab"><i class="fas fa-comment-dots"></i> DESCRIPCIÓN </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h-5" data-toggle="tab" href="#learn_path" role="tab"><i class="fas fa-road"></i> CONTENIDO </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h-5" data-toggle="tab" href="#discussion" role="tab"> COMENTARIOS <i class="fas fa-star"></i></a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="about" class="tab-pane active" data-turbolinks="false" role="tabpanel">
                        <p class="text-left p-4">
                            <%=  markdown(@project.content) %>
                        </p>
                    </div>

                    <div id="learn_path" class="tab-pane p-4" data-turbolinks="false" role="tabpanel">
                        <% @tasks.each do |task| %>
                
                            <% if task.header %>
                                <!--TASK HEADER-->
                                <h5 class="card-title mt-4"><i class="fas fa-graduation-cap"></i>&nbsp; <%= task.title %></h5>
                                <!--/TASK HEADER-->
                            <% else %>
                                <!--TASK ITEMS-->
                                <ul class="list-group list-group-flush">
                                    <%= link_to [task.project, task], class: "list-group-item task-item" do %>  <!--  --->
                                        <% if !@joined %>
                                            <span><i class="fas fa-lock"></i>&nbsp; <%= task.title %></span> 
                                        <% else %>
                                            <%= task.title %></span> 
                                        <% end %>
                                    <% end %>
                                </ul>
                                <!--/TASK ITEMS-->
                            <% end %>
                        
                        <% end %>
                    </div>
                    <div id="discussion" class="tab-pane" data-turbolinks="false" role="tabpanel">
                        <div class="mt-4 p-4">
                            <%= render 'reviews/show' %>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    
    <!-- /RIGHT CARD -->
</div>
<!-- /PROJECT DETAIL -->

<!--Raty script-->
<script>
    $('#average_rating').raty({
        path: '/assets/raty-js/lib/images',
        readOnly: true,
        score: <%= @project.average_rating %>
    });
</script>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
   <script type="text/javascript">
     <% resource.errors.full_messages.each do |value| %>
       toastr.error('<%= value %>')
     <% end %>
   </script>
 <% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
    <%= image_tag 'dark-logo-footer.png', class: "footer-logo", alt: "Footer logo" %>
    <p><i class="fas fa-copyright"></i> 2020 - <%= Time.zone.now.year %>
        <strong>HiGoLearn</strong>, All Rights Reserved.
    </p>
    <div>
        <%= link_to 'Términos y Privacidad', terms_privacy_path, class: "badge badge-success" %>
    </div>
    <br>

    <p>
        <h6>Contact us at </h6>
        <div>
            <strong>jesus@higolearn.com</strong>
        </div>
    </p>

    <div class="rounded-social-buttons">
        <a class="social-button " href="https://www.facebook.com/higolearn" target="_blank"><i class="fab fa-facebook-square"></i></a>
        <a class="social-button " href="https://www.twitter.com/higolearn" target="_blank"><i class="fab fa-twitter-square"></i></a>
        <a class="social-button " href="https://www.github.com/higolearn" target="_blank"><i class="fab fa-github-square"></i></a>
        <a class="social-button " href="https://www.youtube.com/higolearn" target="_blank"><i class="fab fa-youtube-square"></i></a>
        <a class="social-button " href="https://www.instagram.com/higolearn" target="_blank"><i class="fab fa-instagram-square"></i></a>
    </div>
    <br>
    <!--Copyright of images and icons -->
    <div>
        <figcaption>
            <small>
                <strong>Images by</strong>
            </small>
            <a class="social-button " href="https://www.flaticon.com" target="_blank">Flaticon</a> -
            <small>
                <strong>Icons by</strong>
            </small>
            <a class="social-button " href="https://www.fontawesome.com" target="_blank">Font Awesome</a>
        </figcaption>
    </div>
</footer>
<br>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<div class="container fixed-top mt-1">
    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <%= link_to  image_tag('dark-logo.png'), root_path, class: "navbar-brand", alt: "Navbar Logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active p-2">
                    <a class="navbar-brand" href="https://www.facebook.com/higolearn" target="_blank"><i class="fab fa-facebook-square"></i></a>
                    <%= link_to 'Projects', project_index_path, class: "btn nav-link" %>
                </li>
                <% if (!user_signed_in?) %>
                    <li class="nav-item active p-2">
                        <a class="navbar-brand" href="https://www.twitter.com/higolearn" target="_blank"><i class="fab fa-twitter-square"></i></a>
                        <%= link_to "Login", new_user_session_path, class: "btn btn-light nav-link" %>
                    </li>
                    <li class="nav-item active p-2">
                        <a class="navbar-brand" href="https://www.instagram.com/higolearn" target="_blank"><i class="fab fa-instagram-square"></i></a>
                        <%= link_to "Register", new_user_registration_path, class: "btn btn-light nav-link" %>   
                    </li>
                <% else %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= image_tag avatar_url(current_user), class: "img-circle avatar-medium", alt: "Avatar Icon" %>&nbsp;
                            <span>
                                <%= truncate(current_user.fullname, :length => 17, :separator => ' ') %>
                            </span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                            <%= link_to "Projects", myprojects_path, class: "dropdown-item" %>
                            <div class="dropdown-divider"></div>
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
</div>
<br>
<br>
<br>